"""Group-equivariant CNN (p4) for ImageNet classification.

This implements a translation- and rotation-equivariant convolutional network
following Cohen & Welling, "Group Equivariant Convolutional Networks"
(https://arxiv.org/abs/1602.07576), specialised to the ``p4`` group (the group
generated by integer translations and 90-degree rotations, i.e. the cyclic
rotation group ``C4``).

The implementation is self-contained (pure PyTorch, no ``e2cnn``/``escnn``
dependency) and produces raw ``(B, num_classes)`` logits, matching the contract
of the other nets in this package.

Equivariance sketch
--------------------
* ``P4ConvZ2`` lifts a planar signal on ``Z^2`` to a signal on ``p4`` by
  convolving with 4 rotated copies of every filter. Rotating the input by
  90 degrees cyclically permutes the 4 orientation channels (and rotates the
  spatial axes), i.e. the layer is equivariant.
* ``P4ConvP4`` maps signals on ``p4`` to signals on ``p4``. Each output
  orientation uses the input filter rotated spatially *and* cyclically shifted
  along the orientation axis, preserving equivariance.
* Pointwise nonlinearities, spatial pooling and orientation-shared batch-norm
  all commute with the group action.
* A final max over the orientation axis followed by global spatial pooling
  yields a representation that is *invariant* to 90-degree rotations, which is
  then fed to a linear classifier head.
"""

from typing import List, Optional

import torch
import torch.nn.functional as F
from torch import nn

_ROTATIONS = 4  # |C4|: rotations by 0, 90, 180, 270 degrees.


class P4ConvZ2(nn.Module):
    """Lifting convolution mapping a ``Z^2`` signal to a ``p4`` signal.

    Input:  ``(B, in_channels, H, W)``
    Output: ``(B, out_channels, 4, H', W')``
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int = 1,
        padding: int = 0,
        bias: bool = False,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding

        self.weight = nn.Parameter(
            torch.empty(out_channels, in_channels, kernel_size, kernel_size)
        )
        nn.init.kaiming_uniform_(self.weight, a=0, mode="fan_in", nonlinearity="relu")
        self.bias = nn.Parameter(torch.zeros(out_channels)) if bias else None

    def _rotated_weight(self) -> torch.Tensor:
        # Stack 4 spatial rotations of the base filter along a new axis.
        rotations = [
            torch.rot90(self.weight, k=r, dims=(-2, -1)) for r in range(_ROTATIONS)
        ]
        # (4, out, in, k, k) -> (4 * out, in, k, k)
        weight = torch.stack(rotations, dim=0)
        return weight.reshape(_ROTATIONS * self.out_channels, self.in_channels, *weight.shape[-2:])

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        weight = self._rotated_weight()
        out = F.conv2d(x, weight, stride=self.stride, padding=self.padding)
        b, _, h, w = out.shape
        out = out.view(b, _ROTATIONS, self.out_channels, h, w)
        out = out.transpose(1, 2).contiguous()  # (B, out, 4, H, W)
        if self.bias is not None:
            out = out + self.bias.view(1, self.out_channels, 1, 1, 1)
        return out


class P4ConvP4(nn.Module):
    """Group convolution mapping a ``p4`` signal to a ``p4`` signal.

    Input:  ``(B, in_channels, 4, H, W)``
    Output: ``(B, out_channels, 4, H', W')``
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int = 1,
        padding: int = 0,
        bias: bool = False,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding

        self.weight = nn.Parameter(
            torch.empty(out_channels, in_channels, _ROTATIONS, kernel_size, kernel_size)
        )
        nn.init.kaiming_uniform_(self.weight, a=0, mode="fan_in", nonlinearity="relu")
        self.bias = nn.Parameter(torch.zeros(out_channels)) if bias else None

    def _transformed_weight(self) -> torch.Tensor:
        transformed = []
        for r in range(_ROTATIONS):
            # Rotate the filter spatially by r * 90 degrees...
            w = torch.rot90(self.weight, k=r, dims=(-2, -1))
            # ...and cyclically shift the input-orientation axis by r.
            w = torch.roll(w, shifts=r, dims=2)
            transformed.append(w)
        # (4, out, in, 4, k, k) -> (4 * out, in * 4, k, k)
        weight = torch.stack(transformed, dim=0)
        return weight.reshape(
            _ROTATIONS * self.out_channels,
            self.in_channels * _ROTATIONS,
            self.kernel_size,
            self.kernel_size,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        b = x.shape[0]
        weight = self._transformed_weight()
        x = x.reshape(b, self.in_channels * _ROTATIONS, *x.shape[-2:])
        out = F.conv2d(x, weight, stride=self.stride, padding=self.padding)
        _, _, h, w = out.shape
        out = out.view(b, _ROTATIONS, self.out_channels, h, w)
        out = out.transpose(1, 2).contiguous()  # (B, out, 4, H, W)
        if self.bias is not None:
            out = out + self.bias.view(1, self.out_channels, 1, 1, 1)
        return out


class GroupBatchNorm(nn.Module):
    """Batch-norm over ``(B, C, 4, H, W)`` sharing statistics across orientations.

    Sharing statistics across the orientation axis is what keeps normalisation
    equivariant: an orientation permutation of the input leaves the per-channel
    mean/variance unchanged. Implemented with ``BatchNorm3d`` treating the
    orientation axis as an extra spatial dimension.
    """

    def __init__(self, num_channels: int) -> None:
        super().__init__()
        self.bn = nn.BatchNorm3d(num_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.bn(x)


def group_spatial_maxpool(x: torch.Tensor, kernel_size: int, stride: int) -> torch.Tensor:
    """Max-pool spatially, independently per orientation channel.

    With ``kernel_size == stride == 2`` on an even-sized grid this operation is
    *exactly* equivariant to 90-degree rotations, because the set of 2x2 pooling
    windows is mapped onto itself by such a rotation and the max within a window
    is rotation-invariant. This is why downsampling here uses 2x2 pooling rather
    than strided convolutions (which are only approximately equivariant).
    """
    b, c, g, h, w = x.shape
    x = x.reshape(b, c * g, h, w)
    x = F.max_pool2d(x, kernel_size=kernel_size, stride=stride)
    return x.reshape(b, c, g, *x.shape[-2:])


class P4BasicBlock(nn.Module):
    """ResNet-style basic block built from ``p4`` group convolutions.

    All convolutions are stride-1 (equivariance-preserving); spatial
    downsampling is handled externally by ``group_spatial_maxpool``.
    """

    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.conv1 = P4ConvP4(in_channels, out_channels, 3, stride=1, padding=1)
        self.bn1 = GroupBatchNorm(out_channels)
        self.conv2 = P4ConvP4(out_channels, out_channels, 3, stride=1, padding=1)
        self.bn2 = GroupBatchNorm(out_channels)

        self.downsample: Optional[nn.Module] = None
        if in_channels != out_channels:
            self.downsample = nn.Sequential(
                P4ConvP4(in_channels, out_channels, 1, stride=1, padding=0),
                GroupBatchNorm(out_channels),
            )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x if self.downsample is None else self.downsample(x)
        out = F.relu(self.bn1(self.conv1(x)), inplace=True)
        out = self.bn2(self.conv2(out))
        out = out + identity
        return F.relu(out, inplace=True)


class EquivariantNet(nn.Module):
    """Rotation- and translation-equivariant CNN (p4) for image classification.

    The backbone mirrors a ResNet-18 layout but every convolution is a ``p4``
    group convolution, so feature maps carry an explicit orientation axis. The
    channel widths are scaled down (``base_channels`` defaults to 32) because
    each group convolution already replicates its filters over 4 orientations,
    keeping the parameter/compute budget comparable to a plain CNN.

    Args:
        num_classes: Number of output classes.
        in_channels: Number of input image channels (3 for RGB).
        base_channels: Width of the first stage (subsequent stages double it).
        layers: Number of basic blocks in each of the 4 stages.
        stem_kernel_size: Kernel size of the lifting stem convolution.
    """

    def __init__(
        self,
        num_classes: int = 1000,
        in_channels: int = 3,
        base_channels: int = 32,
        layers: Optional[List[int]] = None,
        stem_kernel_size: int = 7,
    ) -> None:
        super().__init__()
        if layers is None:
            layers = [2, 2, 2, 2]
        if len(layers) != 4:
            raise ValueError(f"`layers` must have length 4, got {len(layers)}.")

        c1, c2, c3, c4 = (
            base_channels,
            base_channels * 2,
            base_channels * 4,
            base_channels * 8,
        )

        # Lifting stem: Z^2 -> p4. A stride-2 conv is used here purely for
        # compute efficiency; it is the only mildly non-90-degree-equivariant
        # operation in the network. All subsequent downsampling uses exactly
        # equivariant 2x2 max-pooling.
        self.stem = P4ConvZ2(
            in_channels,
            c1,
            kernel_size=stem_kernel_size,
            stride=2,
            padding=stem_kernel_size // 2,
        )
        self.stem_bn = GroupBatchNorm(c1)

        self.layer1 = self._make_stage(c1, c1, layers[0])
        self.layer2 = self._make_stage(c1, c2, layers[1])
        self.layer3 = self._make_stage(c2, c3, layers[2])
        self.layer4 = self._make_stage(c3, c4, layers[3])

        self.classifier = nn.Linear(c4, num_classes)

    @staticmethod
    def _make_stage(
        in_channels: int, out_channels: int, num_blocks: int
    ) -> nn.Sequential:
        blocks = [P4BasicBlock(in_channels, out_channels)]
        for _ in range(num_blocks - 1):
            blocks.append(P4BasicBlock(out_channels, out_channels))
        return nn.Sequential(*blocks)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.stem_bn(self.stem(x)), inplace=True)  # 224 -> 112
        x = group_spatial_maxpool(x, kernel_size=2, stride=2)  # 112 -> 56

        x = self.layer1(x)  # 56
        x = group_spatial_maxpool(x, kernel_size=2, stride=2)  # 56 -> 28
        x = self.layer2(x)  # 28
        x = group_spatial_maxpool(x, kernel_size=2, stride=2)  # 28 -> 14
        x = self.layer3(x)  # 14
        x = group_spatial_maxpool(x, kernel_size=2, stride=2)  # 14 -> 7
        x = self.layer4(x)  # 7

        # Max over orientation axis -> rotation-invariant features.
        x = x.amax(dim=2)  # (B, C, H, W)
        # Global average pool over space.
        x = F.adaptive_avg_pool2d(x, 1).flatten(1)  # (B, C)

        return self.classifier(x)
