_target_: codecarbon.EmissionsTracker
project_name: "imagine-hackathon-2026"
experiment_name: ${experiment_name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
measure_power_secs: 5
log_time_series: True
log_level: "WARNING"
output_dir: ${paths.codecarbon_dir}${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
tracking_mode: "process"
gpu_ids: "0"  # Single-GPU tracking
save_to_file: True
log_interval: 1
save_to_api: True
api_call_interval: 60  # Will log to the API every 5 minutes (5 * 60)
save_to_wandb: True

# From Lightning's WandbLogger config
wandb_kwargs:
  name: ${oc.select:logger.wandb.name,null}
  group: ${oc.select:logger.wandb.group,null}
  entity: ${oc.select:logger.wandb.entity,null}
  tags: ${oc.select:logger.wandb.tags,null}
  save_dir: ${oc.select:logger.wandb.save_dir,null}
  offline: ${oc.select:logger.wandb.offline,null}
  id: ${oc.select:logger.wandb.id,null}
  project: ${oc.select:logger.wandb.project,null}
