# @package _global_

# example hyperparameter optimization of some experiment with basic Hydra:
# uv run src/train.py hparams_search=basic experiment=example

hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    params:
      module.optimizer.lr: range(0.007, 0.01, step=0.002)
      datamodule.batch_size: choice(512)

tags: ["hyperparam", "train"]