# @package _global_

defaults:
  - _self_
  - datamodule: default
  - module: vit_s_16
  - trainer: imagenet_vit_s_16
  - logger: null
  - callbacks: null
  - paths: default
  - extras: default
  - hydra: eval
  - codecarbon: null
  - experiment: null
  - hparams_search: null
  - debug: null
  - override /module: metaformer_hybrid_s12

# TODO Write your team name
team_name: arch
tags: ["explore", "evaluate"]

seed: 0

trainer:
  precision: 16-mixed

module:
  compile: false

checkpoints: [
  "metaformer_hybrid_s12/2026-07-02/14-24-40/checkpoints/last.ckpt",
  "vit_with_convstem_w_similar_lfops/2026-07-01/12-36-51/checkpoints/last.ckpt",
]
